[workspace]
members = ["rgdext", "rgdext_shared", "rgdext_serverutil", "rgdext_client", "map_benchmark"]
resolver = "2"

[workspace.dependencies]
godot = {version = "0.3.5", features = ["register-docs"]}
