[package]
name = "rgdext"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = {workspace = true}
rgdext_shared = {path = "../rgdext_shared"}
ctrlc = "3.4.7"
